### ISSUE TITLE
Only grass on Dirt are generating MC -> 1.13.x and up

### ISSUE THREAD

**Issue by Denaris01** [fof1092/AlmostFlatLandsReloaded#2]
Hello,

i use the bukkit.yml to generate (no multiworld or multiverse installed) a world but there are only grass and no flowers and trees. i testet it whit spigot 1.16.1 and 1.16.3. I fly many chunks but overall are only dirt and grass.

Can you help?
Thank you

```
worlds:
  world:
    generator: AlmostFlatLandsReloaded
```

![2020-09-16_12 09 12](https://user-images.githubusercontent.com/22527229/93324407-20b62b80-f816-11ea-8d43-3071433bacfc.png)

Your Config looks ok:
```
Version: 1.25
GameVersion:
  SetOwn: false
  Version: v1_16_R2
ColoredConsoleText: true
ShowUpdateMessage: true
World:
  Height: 32
  Biome: PLAINS
  GrassChance: 14
  FlowerChance: 1
  TreeChance: 15
  TreeTypes:
  - TREE
  - BIRCH
  - BIG_TREE
  WaterHeight: -1
  GenerateOres: true
  UndergroundMaterials:
  - STONE
  - STONE
  - COBBLESTONE
  PreGroundMaterials:
  - DIRT
  GroundMaterials:
  - GRASS
  WaterGroundMaterials:
  - SAND
```

**Comment by Denaris01** [comment]
Ok, i have found the "bug": It generarte Grass and no Grass Block. Are you using Namespaced ID or Block ID? I think there are a confusion (GRASS vs GRASS_BLOCK). In your config are:
![Screen-2020-09-16_12-37-36](https://user-images.githubusercontent.com/22527229/93326753-9bcd1100-f819-11ea-9a37-3ce4766b907a.png)
```
GroundMaterials:
  - GRASS
```
This works for MC 1.16.1:
```
GroundMaterials:
  - GRASS_BLOCK
```
**"GRASS" works only <-- MC 1.12.2 and "GRASS_BLOCK" --> MC 1.13.x** and up
![2020-09-16_12 43 23](https://user-images.githubusercontent.com/22527229/93327662-f4e97480-f81a-11ea-990c-56789654c203.png)

**Comment by fof1092** [comment]
Thanks for the info, I have fixed the problem in the latest version. :)
